name: Golang Integration Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version
      - name: Setup Environment
        env:
          PG_DB_HOST: localhost
          PG_DB_PORT: 5432
          PG_DB_USER: postgres
          PG_DB_PASSWORD: postgres
          PG_DB_NAME: postgres
        run: |
          go mod tidy
          go test test/DBConnection_test.go