name: Hello world workflow
# Events Workflow running push,pull_request,fork
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello, world!"
