# name: Events Input
# run-name: ${{ github.actor }} Learning Events Input
# on:
#   workflow_call:
#     inputs:
#       username:
#         description: 'A username passed from the caller workflow'
#         default: 'john-doe'
#         required: false
#         type: string

# jobs:
#   print-username:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Print the input name to STDOUT
#         run: echo The username is ${{ inputs.username }}

name: Workflow with Input

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: true
        default: 'Default value'

jobs:
  process_input:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input
        run: |
          echo "Input value: ${{ github.event.inputs.parameter_name }}"