name: Learn Issue Events GitHub Actions

on:
  issues:
    types: [opened]

jobs:
  print-event-attribute:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Events
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment using GitHub CLI
        env:
          ORGANIZATION: ${{ github.event.repository.owner.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }} # Use the issue number from the event
          COMMENT_BODY: |
            This is a test comment.
            You can add multiple lines.
            Markdown is supported.
        run: |
          gh api repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body="${COMMENT_BODY}"
