name: Schedule Events GitHub Actions
run-name: Schedule Events GitHub Actions
on:
  schedule:
    # <minute> <hour> <day of month> <month> <day of week>
    - cron: '15,30 7,19 * * *' # Menjadwalkan tindakan pada menit ke-1 setiap jam pada pukul 07:01 dan 19:01 (waktu UTC)

jobs:
  schedule_print:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Print Schedule
        run: echo "${{ github.actor }} is learning GitHub Actions Events Schedule"
